# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e991d6768057c79131ed609ee1cda15b6de382c63a0c4fcd091844f4354d91394185e5eec0ace78191bbd098c3d9ec8633bb04524d2a329df6bba797d1e1f3b7

test:
  secret_key_base: 076df8a8dc54b6a16cd54141b5b641fe8e174b95052c73d743b892f4c26576614d86d1595ccbc9b826c62a4ccab861880c2e3ef476ea022564aeeca12d16bce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
